# Generated by Django 5.0.6 on 2024-10-30 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=100)),
                ('dosage', models.PositiveIntegerField(max_length=50)),
                ('dosage_unit', models.CharField(choices=[('ml', 'Ml')], max_length=2)),
                ('frequency', models.PositiveIntegerField(max_length=50)),
                ('start_date', models.DateField(auto_created=None)),
                ('end_date', models.DateField(auto_created=None)),
                ('time', models.TimeField(auto_created=None, auto_now=None, auto_now_add=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
