# Generated by Django 5.0.6 on 2024-10-30 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='dosage',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='frequency',
            field=models.PositiveIntegerField(),
        ),
    ]
