# Generated by Django 5.0.6 on 2024-10-30 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_medicine_dosage_alter_medicine_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='dosage_unit',
            field=models.CharField(choices=[('MG', 'mg'), ('ML', 'ml')], default='MG', max_length=2),
        ),
    ]
